### ISSUE TITLE
AzGovVizParallel.ps1 throws in some tenants

### ISSUE THREAD

**Issue by AsbjornNielsen** [JulianHayward/Azure-MG-Sub-Governance-Reporting#188]
**AzGovViz version**
Latest (currently AzGovVizParallel.ps1 is 32737fb)

**CodeRunPlatform**
Azure DevOps

**Describe the bug**
We use AzGovViz to pull out information from several tenants. AzGovVizParallel.ps1 runs without any problems in some of the tenants, but fails/throws in others.
The script throws at line 34088 - if ($htAvailablePrivateEndpointTypes.Keys.Count -gt 0) (line 34082).

I have tried setting $SubscriptionId4AzContext to different IDs, without luck

However, if I out-comment the throwing line (34088), everything seems to work fine in all tenants. My temporary, not very satisfactory, hack is to have a step in between the checkout and the powershell task where I outcomment the line.

**Screenshots**
![PipelineError](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/assets/9654937/c7121f17-1576-432c-bbc3-d738779fb08b)

**Additional context**

**Comment by JulianHayward** [comment]
@AsbjornNielsen can you try some more sub ids, please?
If that collection fails (or you manipulate it to continue), in turn we cannot determine PE capable services and therefore some other enriched outputs will be incorrect.

**Comment by JulianHayward** [comment]
hi @AsbjornNielsen any news?

**Comment by JulianHayward** [comment]
@AsbjornNielsen strike1 :)

**Comment by ReneRebsdorf** [comment]
@JulianHayward this was the issue I was mentioning yesterday.
I will test this during this week to determine if it still is relevant.

I'll write back here with an update.

**Comment by ReneRebsdorf** [comment]
@JulianHayward This is fixed, I experienced the error in this issue at one client where the subscription we run against using SubscriptionId4AzContext did not have the microsoft.network provider registered. After registering the provider, the solution works without issues.

Is it worth adding a GET Rest call if this error is observed, or if the parameter is provided, to verify if the provider is missing registration, as it is guaranteed that will cause this error - so that information can be included for that explicit scenario?

**Comment by JulianHayward** [comment]
@ReneRebsdorf see the changes from [6.4.0](https://github.com/JulianHayward/Azure-MG-Sub-Governance-Reporting/releases/tag/6.4.0)
optimize getting private endpoint capable resource types / in case resource provider 'microsoft.network' is not registered, **try with next available subscription instead of throwing**
but yes we could also verify the provider state informational
